worldofsfx/beatport/models.py
from worldofsfx.database import db

worldofsfx/buzz/models.py
from worldofsfx.database import db

worldofsfx/events/models.py
from worldofsfx.database import db

worldofsfx/example/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
    An example models.py for use with worldofsfx

    Useage::

        from worldofsfx.database import db

        class FooModel(db.Model):

            __tablename__ = 'foos'

            id = db.Column(db.Integer, primary=True)
            name = db.Column(db.String(30), nullable=False)
"""

from worldofsfx.database import db

worldofsfx/wos/models.py
"""
    An wos models.py for use with worldofsfx

    Useage::

        from worldofsfx.database import db

        class FooModel(db.Model):

            __tablename__ = 'foos'

            id = db.Column(db.Integer, primary=True)
            name = db.Column(db.String(30), nullable=False)
"""

from worldofsfx.database import db

worldofsfx/__init__.py
import os
import sys
from flask import Flask
from flask_environments import Environments

from worldofsfx.database import db

from worldofsfx.wos.views import wos
from worldofsfx.events.views import events
from worldofsfx.buzz.views import buzz
from worldofsfx.beatport.views import beatport


def create_app(environment="DEVELOPMENT"):
    """worldofsfx application factory.

    This function defines a re-usable pattern for instantiating and creating
    application objects.

    :param str environment: Specify the name of the configuration object used
                            to build this application object

    Usage::
        from worldofsfx import create_app
        from unittest import TestCase

        class MyTest(TestCase):

            def setUp(self):
                self.app = create_app(environment="TESTING")

    :returns: flask application
    :rtype: :obj:`flask.Flask`
    """
    if not environment:
        env_name = 'DEVELOPMENT'
    else:
        env_name = environment.upper()
    app = Flask(__name__)
    env = Environments(app, default_env=env_name)
    env.from_object('worldofsfx.config')
    # Try to load a private config file from the WOS_PRIVATES environment variable.
    wos_privates_filepath = os.getenv('WOS_PRIVATES')
    if wos_privates_filepath:
        try:
            sys.path.append(os.path.dirname(wos_privates_filepath))
            module_name = os.path.basename(wos_privates_filepath).strip('.py')
            env.from_object(__import__(module_name))
        except:
            pass

    app.template_folder = app.config.get('TEMPLATE_FOLDER', 'templates')

    app.register_blueprint(wos)
    app.register_blueprint(events)
    app.register_blueprint(buzz)
    app.register_blueprint(beatport)

    db.init_app(app)

    return app

worldofsfx/beatport/views.py
from flask import Blueprint, render_template

#: Specify each model defined in your models.py for each app here. This will
#: allow SQA to pick them up when the application is initialized
from worldofsfx.beatport.models import *

beatport = Blueprint('beatport', __name__, url_prefix='/beatport')


@beatport.route('/')
def index():
    return render_template("beatport/index.html")

worldofsfx/buzz/views.py
from flask import Blueprint, render_template

#: Specify each model defined in your models.py for each app here. This will
#: allow SQA to pick them up when the application is initialized
from worldofsfx.buzz.models import *

buzz = Blueprint('buzz', __name__, url_prefix='/buzz')


@buzz.route('/')
def index():
    return render_template("buzz/index.html")

worldofsfx/events/views.py
from flask import Blueprint, render_template

#: Specify each model defined in your models.py for each app here. This will
#: allow SQA to pick them up when the application is initialized
from worldofsfx.events.models import *

events = Blueprint('events', __name__, url_prefix='/events')


@events.route('/')
def index():
    return render_template("events/index.html")

worldofsfx/example/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

#: Specify each model defined in your models.py for each app here. This will
#: allow SQA to pick them up when the application is initialized
from .models import *

mod = Blueprint('example', __name__)


@mod.route('/')
def home():
    return render_template("example/home.html")

worldofsfx/wos/views.py
from flask import Blueprint, render_template

#: Specify each model defined in your models.py for each app here. This will
#: allow SQA to pick them up when the application is initialized
from worldofsfx.wos.models import *

wos = Blueprint('wos', __name__)


@wos.route('/')
def home():
    return render_template("wos/index.html")

worldofsfx/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>World of SFX {% block titlesuffix %}{% endblock %}</title>

<link rel="stylesheet" href="css/main.css" type="text/css" />

<!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lte IE 7]>
    <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
<!--[if lt IE 7]>

    <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->
    <link href="{{ url_for('static', filename='css/uikit.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='css/uikit.almost-flat.min.css') }}" rel="stylesheet" type="text/css">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{{ url_for('static', filename='js/uikit.min.js') }}"></script> 
</head>

<body id="index" class="home">
    <nav class="uk-navbar">
        <div class="uk-container uk-container-center">
            <a href="#" class="uk-navbar-brand">World of SFX</a>
            <ul class="uk-navbar-nav uk-hidden-small uk-navbar-attached">
                <li class="uk-active"><a href="{{ url_for('wos.home') }}">Home</a></li>
                <li><a href="{{ url_for('buzz.index') }}">Buzz</a></li>
                <li><a href="{{ url_for('events.index') }}">Events</a></li>
                <li><a href="{{ url_for('beatport.index') }}">Beatport</a></li>
                <li><a href="">Tickets</a></li>
                <li><a href="">Heroes of SFX</a></li>
                <li><a href="">Media</a></li>
            </ul>
            <div class="uk-navbar-flip">
                <a href="#my-id" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas="{target:'#my-id'}"></a>
            </div>
        </div>
    </nav>

    <div id="my-id" class="uk-offcanvas">
        <div class="uk-offcanvas-bar">
            <ul class="uk-nav uk-nav-offcanvas" data-uk-nav>
                <li class="uk-active"><a href="{{ url_for('wos.home') }}">Home</a></li>
                <li><a href="{{ url_for('buzz.index') }}">Buzz</a></li>
                <li><a href="{{ url_for('events.index') }}">Events</a></li>
            </ul>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

worldofsfx/templates/beatport/index.html
{% extends "base.html" %}

{% block content %}

    <!-- Needed for padding at top of body, to look more like Bootstrap's example -->
    <br>

    <div class="uk-container uk-container-center">
        <h1>Beatport</h1>
    </div>
{% endblock %}

worldofsfx/templates/buzz/index.html
{% extends "base.html" %}

{% block content %}

<!-- Needed for padding at top of body, to look more like Bootstrap's example -->
<br>

<div class="uk-container uk-container-center">
    <h1>Buzz</h1>
    <img src="http://img4.wikia.nocookie.net/__cb20131002012743/disney/images/thumb/b/b4/Buzz_Lightyear.png/258px-Buzz_Lightyear.png">
</div>
{% endblock %}

worldofsfx/templates/events/index.html
{% extends "base.html" %}

{% block content %}

<!-- Needed for padding at top of body, to look more like Bootstrap's example -->
<br>

<div class="uk-container uk-container-center">
    <h1>SFX events</h1>
    <p>Rejoice, for here be events!</p>
    <p>Much events, such wow</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
</div>
{% endblock %}

worldofsfx/templates/wos/buzz.html
{% extends "base.html" %}

{% block content %}

<!-- Needed for padding at top of body, to look more like Bootstrap's example -->
<br>

<div class="uk-container uk-container-center">
    <h1>Buzz</h1>
    <img src="http://img4.wikia.nocookie.net/__cb20131002012743/disney/images/thumb/b/b4/Buzz_Lightyear.png/258px-Buzz_Lightyear.png">
</div>
{% endblock %}

worldofsfx/templates/wos/events.html
{% extends "base.html" %}

{% block content %}

<!-- Needed for padding at top of body, to look more like Bootstrap's example -->
<br>

<div class="uk-container uk-container-center">
    <h1>SFX events</h1>
    <p>Rejoice, for here be events!</p>
    <p>Much events, such wow</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
    <p>many fun&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; such tickets</p>
</div>
{% endblock %}

worldofsfx/templates/wos/index.html
{% extends "base.html" %}

{% block content %}

<!-- Needed for padding at top of body, to look more like Bootstrap's example -->
<br>

<div class="uk-container uk-container-center">
    <h1>UIKit starter template</h1>
    <p>Welcome to the World of SFX, powered by Paylogic!</p>
</div>
{% endblock %}